### ISSUE TITLE
support for 4.7? 4.6?

### ISSUE THREAD

**Issue by JoeMurray** [twomice/me.twomice.civicrm.aggregatehouseholdcontributions#2]
Hi Allen,
Just wondering if you plan to update to support new versions of CiviCRM?
Cheers,
Joe

**Comment by twomice** [comment]
Yes, a release supporting 4.6 is upcoming.

**Comment by twomice** [comment]
Version 1.2 (https://civicrm.org/extensions/aggregate-household-contributions-report/12) now supports CiviCRM 4.6.
