### ISSUE TITLE
Problem after upgrade to 5.3.1

### ISSUE THREAD

**Issue by timatidg** [twomice/me.twomice.civicrm.aggregatehouseholdcontributions#8]
I had this problem after another upgrade and can't figure out how I solved it!

Extension installed, Enabled | ver 1.2 and at /home/MYSITEDIR/public_html/sites/all/civiextensions/me.twomice.civicrm.aggregatehouseholdcontributions

All existing reports error out with:

Fatal error: require_once(): Failed opening required 'CRM/Aggregatehouseholdcontributions/Report/Form/Contribute/AggregatedHouseholds.php' (include_path='/home/MYSITEDIR/public_html/sites/all/civiextensions/com.iatspayments.civicrm/:/home/MYSITEDIR/public_html/sites/all/civiextensions/de.systopia.householdmerge-1.1.beta/:/home/MYSITEDIR/public_html/sites/all/civiextensions/com.pogstone.fancytokens/:/home/MYSITEDIR/public_html/sites/all/civiextensions/nz.co.fuzion.cssinline/:.:/home/MYSITEDIR/public_html/sites/all/modules/civicrm:/home/MYSITEDIR/public_html/sites/all/modules/civicrm/packages:.:/home/MYSITEDIR/public_html/sites/all/modules/civicrm:/home/MYSITEDIR/public_html/sites/all/modules/civicrm/packages:/home/MYSITEDIR/public_html/sites/all/modules/civicrm/vendor/tecnickcom:/home/MYSITEDIR/public_html/sites/all/modules/civicrm/vendor/phpseclib/phpseclib/phpseclib:/home/MYSITEDIR/public_html/sites/all/modules/civicrm/vendor/pear/pear_exception:/home/MYSITEDIR/public_html/ in /home/MYSITEDIR/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php on line 451

A file by that name is at: 
/home/MYSITEDIR/public_html/sites/default/files/civicrm/custom/customphp/CRM/Report/Form/Contribute/AggregatedHouseholds.php

Copying it to:
/home/MYSITEDIR/public_html/sites/default/files/civicrm/custom/customphp/CRM/Aggregatehouseholdcontributions/Report/Form/Contribute/AggregatedHouseholds.php
**_does NOT fix it._**

The code referenced is 
_require_once str_replace('_', DIRECTORY_SEPARATOR, $className) . '.php';
in the snippet below
```
$ext = CRM_Extension_System::singleton()->getMapper();
      if ($ext->isExtensionClass($className)) {
        require_once $ext->classToPath($className);
      }
      else {
               require_once str_replace('_', DIRECTORY_SEPARATOR, $className) . '.php';
      }
```

**Comment by timatidg** [comment]
Got it working by adding that file here:
/home/MYSITEDIR/public_html/sites/all/modules/civicrm/CRM/Aggregatehouseholdcontributions/Report/Form/Contribute/AggregatedHouseholds.php

**Comment by twomice** [comment]
Thanks for reaching out @timatidg. I'm glad you found a solution, but I should point out a couple of things.

1. Placing the file under the CiviCRM core file structure, as you describe, will cause the file to go missing again at your next CiviCRM upgrade.
2. The file "AggregatedHouseholds.php" was removed in extension version 1.2. Although you're showing that as the current version, the file itself is from a previous version, and it won't provide the latest functionality for the report.
3. I suspect the bad behavior you're seeing is caused by something going awry in your upgraded of the extension from its previous version(s).
4. To get the latest report functionality and avoid future problems at your next CiviCRM upgrade, I recommend removing all instances of that file, completely uninstalling the extension, and then installing the extension again.

If you still have problems after that, please re-open this ticket to request more help. Or if you have good luck with that approach, please let us know with a comment here. Thanks!

**Comment by timatidg** [comment]
@twomice (Allen), I found I can't uninstall. (I had to wait to try this until done with a reporting period for the client,) I tried deleting all the files: AggregatedHouseholds.php from everywhere and then everything in  me.twomice.civicrm.aggregatehouseholdcontributions. Re-enabled and was back with the original error. Restored AggregatedHouseholds.php in (ONLY) the wrong place and it works fine again. Sigh.

Uninstalling extension errors with
Drupal log:

```
civicrm/admin/extensions?action=delete&id=me.twomice.civicrm.aggregatehouseholdcontributions&key=me.twomice.civicrm.aggregatehouseholdcontributions
--
$Fatal Error Details = Array ( [callback] => Array ( [0] => CRM_Core_Error [1] => handle ) [code] => -2 [message] => DB_DataObject Error: delete: No condition specifed for query [mode] => 16 [debug_info] => [type] => DB_DataObject_Error [user_info] => [to_string] => [db_dataobject_error: message="DB_DataObject Error: delete: No condition specifed for query" code=-2 mode=callback callback=CRM_Core_Error::handle prefix="" info=""] )
```

From Civi log:
`
Oct 05 17:46:27  [info] $backTrace = #0 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Core/Error.php(232): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 [internal function](): CRM_Core_Error::handle(Object(DB_DataObject_Error))
#2 /home/MYSITE/public_html/sites/all/modules/civicrm/packages/PEAR.php(921): call_user_func((Array:2), Object(DB_DataObject_Error))
#3 /home/MYSITE/public_html/sites/all/modules/civicrm/packages/DB/DataObject/Error.php(44): PEAR_Error->__construct("DB_DataObject Error: delete: No condition specifed for query", -2, 16, (Array:2))
#4 /home/MYSITE/public_html/sites/all/modules/civicrm/packages/PEAR.php(577): DB_DataObject_Error->__construct("delete: No condition specifed for query", -2, 16, (Array:2), NULL)
#5 [internal function](): PEAR::_raiseError(NULL, "delete: No condition specifed for query", -2, NULL, NULL, NULL, "DB_DataObject_Error")
#6 /home/MYSITE/public_html/sites/all/modules/civicrm/packages/PEAR.php(237): call_user_func_array((Array:2), (Array:7))
#7 /home/MYSITE/public_html/sites/all/modules/civicrm/packages/DB/DataObject.php(4231): PEAR::__callStatic("raiseError", (Array:6))
#8 /home/MYSITE/public_html/sites/all/modules/civicrm/packages/DB/DataObject.php(4231): PEAR::raiseError("delete: No condition specifed for query", -2, NULL, NULL, NULL, "DB_DataObject_Error")
#9 /home/MYSITE/public_html/sites/all/modules/civicrm/packages/DB/DataObject.php(1442): DB_DataObject->raiseError("delete: No condition specifed for query", -2)
#10 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Core/DAO.php(593): DB_DataObject->delete(FALSE)
#11 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Core/BAO/OptionValue.php(265): CRM_Core_DAO->delete()
#12 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Extension/Manager/Report.php(101): CRM_Core_BAO_OptionValue::del(NULL)
#13 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Extension/Manager.php(368): CRM_Extension_Manager_Report->onPreUninstall(Object(CRM_Extension_Info))
#14 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Admin/Form/Extensions.php(180): CRM_Extension_Manager->uninstall((Array:1))
#15 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Core/Form.php(466): CRM_Admin_Form_Extensions->postProcess()
#16 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Core/StateMachine.php(160): CRM_Core_Form->mainProcess()
#17 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")
#18 /home/MYSITE/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Admin_Form_Extensions), "next")
#19 /home/MYSITE/public_html/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Admin_Form_Extensions), "next")
#20 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Core/Controller.php(351): HTML_QuickForm_Page->handle("next")
#21 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(398): CRM_Core_Controller->run()
#22 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Core/Page/Basic.php(156): CRM_Core_Page_Basic->edit(8, NULL)
#23 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Admin/Page/Extensions.php(121): CRM_Core_Page_Basic->run()
#24 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(309): CRM_Admin_Page_Extensions->run((Array:3), NULL)
#25 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(84): CRM_Core_Invoke::runItem((Array:16))
#26 /home/MYSITE/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(52): CRM_Core_Invoke::_invoke((Array:3))
#27 /home/MYSITE/public_html/sites/all/modules/civicrm/drupal/civicrm.module(445): CRM_Core_Invoke::invoke((Array:3))
#28 [internal function](): civicrm_invoke("admin", "extensions")
#29 /home/MYSITE/public_html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#30 /home/MYSITE/public_html/index.php(21): menu_execute_active_handler()
#31 {main}`

**Comment by twomice** [comment]
I half expect that this is not possible, but here's a request: If you can help me by creating a list of steps to reproduce this problem on a new civicrm installation, I'll be able to examine and debug from here. 

Admittedly, that's probably a hard thing to do. It probably would involve something like "install civicrm 4.6.whatever; install extension version 1.1; upgrade civicrm to 5.3.whatever; upgrade extension to latest version; etc. ..." But if you can do it, it would give me a way to debug and produce a fix, one which would be useful to other users of this extension.

An alternative would be to just leave it as-is, since it works for you now. Then you'll need to repeat these steps again next time you upgrade CiviCRM.
